FROM node:20-alpine

RUN apk add --no-cache postgresql-client bash dos2unix

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

COPY . .

EXPOSE 3000

# Fix CRLF line endings for Windows hosts and make entrypoint executable
RUN dos2unix ./scripts/dev-entrypoint.sh && chmod +x ./scripts/dev-entrypoint.sh

ENTRYPOINT ["./scripts/dev-entrypoint.sh"]
