import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

export interface BiodataPdfData {
  fullName?: string | null;
  dateOfBirth?: string | null;
  phone?: string | null;
  email?: string | null;
  courseCompletedNames: string[];
  certificationCodes: string[];
  educationalQualification?: string | null;
  yearOfPassing?: number | null;
  address?: string | null;
  languagesKnown: string[];
  skillLabels: string[];
  preferredJobLocation?: string | null;
  preferredJobType?: string | null;
  careerObjective?: string | null;
}

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica" },
  header: {
    fontSize: 18,
    marginBottom: 20,
    textAlign: "center",
    fontWeight: "bold",
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: "bold" as const,
    marginTop: 16,
    marginBottom: 8,
    backgroundColor: "#f0f0f0",
    padding: 4,
  },
  row: { flexDirection: "row", marginBottom: 4 },
  label: { width: 160, fontWeight: "bold" as const },
  value: { flex: 1 },
  footer: {
    position: "absolute" as const,
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 9,
    color: "#666",
  },
});

function Field({
  label,
  value,
}: {
  label: string;
  value?: string | number | null;
}) {
  return (
    <View style={styles.row}>
      <Text style={styles.label}>{label}:</Text>
      <Text style={styles.value}>{value ?? "-"}</Text>
    </View>
  );
}

function ListField({
  label,
  items,
}: {
  label: string;
  items: string[];
}) {
  return (
    <View style={styles.row}>
      <Text style={styles.label}>{label}:</Text>
      <Text style={styles.value}>
        {items.length > 0 ? items.join(", ") : "-"}
      </Text>
    </View>
  );
}

export function BiodataPdfDocument({ data }: { data: BiodataPdfData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>Candidate Biodata</Text>

        <Text style={styles.sectionTitle}>Personal Information</Text>
        <Field label="Full Name" value={data.fullName} />
        <Field label="Date of Birth" value={data.dateOfBirth} />
        <Field label="Phone" value={data.phone} />
        <Field label="Email" value={data.email} />

        <Text style={styles.sectionTitle}>Education</Text>
        <Field label="Qualification" value={data.educationalQualification} />
        <Field label="Year of Passing" value={data.yearOfPassing} />
        <ListField
          label="Courses Completed"
          items={data.courseCompletedNames}
        />
        <ListField label="Certifications" items={data.certificationCodes} />

        <Text style={styles.sectionTitle}>Skills &amp; Languages</Text>
        <ListField label="Languages Known" items={data.languagesKnown} />
        <ListField label="Skills" items={data.skillLabels} />

        <Text style={styles.sectionTitle}>Career Preferences</Text>
        <Field
          label="Preferred Location"
          value={data.preferredJobLocation}
        />
        <Field label="Preferred Job Type" value={data.preferredJobType} />
        <Field label="Career Objective" value={data.careerObjective} />

        <Text style={styles.sectionTitle}>Address</Text>
        <Field label="Address" value={data.address} />

        <Text style={styles.footer}>
          Generated by GTEC Thodupuzha — Candidate Profile Export
        </Text>
      </Page>
    </Document>
  );
}
